name: Sync Github Repos To Gitee

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync Github Repos To Gitee  # 名字随便起
      uses: tanktest@v1.1  # 使用Yikun/hub-mirror-action
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
      with:
        source-repo: "git@github.com:tanzhiliangit/my-scripts.git"
        destination-repo: "git@gitee.com:tanzhilian/my-scripts.git"

